### ISSUE TITLE
Remove references to OpcUA from IoTApi

### ISSUE THREAD

**Issue by ddobric** [UniversityOfAppliedSciencesFrankfurt/SmartWorld#2]
@aqib0080 your last checkin does not build. Please Remove OPCUA references from IoTApi.

**Comment by aqib0080** [comment]
@ddobric  Sir I have removed the said refferences and made a new comit accordingly. On my system the code is building properly. 
Regards

**Comment by aqib0080** [comment]
Hello,
Can you please explain what your last email mean.
Regards
